### ISSUE TITLE
Addition to Readme.md

### ISSUE THREAD

**Issue by juliencombattelli** [juliencombattelli/OpenGL-Test#1]
You should really add that to your Readme 👍 
<br>
<img src="http://i.imgur.com/Q0vFcHd.png">

**Comment by juliencombattelli** [comment]
Yes, I will push that soon ! Thanks for the help !

**Comment by juliencombattelli** [comment]
Your welcome !

**Comment by juliencombattelli** [comment]
Why am I talking to myself ?

**Comment by juliencombattelli** [comment]
I must feel really alone !

**Comment by juliencombattelli** [comment]
Please, someone, help !

**Comment by juliencombattelli** [comment]
Really, is there anybody who could help ?

**Comment by juliencombattelli** [comment]
Yes, me !

**Comment by juliencombattelli** [comment]
Who ?

**Comment by juliencombattelli** [comment]
Me, Mario !

**Comment by juliencombattelli** [comment]
Wait a minute, what's happening here ?

**Comment by juliencombattelli** [comment]
I don't know, I just arrived

**Comment by juliencombattelli** [comment]
I'm searching for peach. Is she here ?

**Comment by reivax-boucoi** [comment]
Whow this guy is weird

**Comment by reivax-boucoi** [comment]
Am I the only one to think that ?

**Comment by sarthou** [comment]
No, definitely, he is weird ....

<img src="https://pics.me.me/maybe-youre-weird-butim-special-16122432.png">
